apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namePrefix: prod-

labels:
  - pairs:
      environment: production
    includeSelectors: false

patches:
  - patch: |
      - op: replace
        path: /spec/containers/0/resources/limits/cpu
        value: 4000m
      - op: replace
        path: /spec/containers/0/resources/limits/memory
        value: 8Gi
    target:
      kind: ClusterServingRuntime
