apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - mlflow-application.yaml
  - kubeflow-application.yaml
  - kserve-application.yaml
  - monitoring-application.yaml

labels:
  - pairs:
      environment: staging
      managed-by: argocd
    includeSelectors: false
