apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - ../../projects/mlops-core.yaml

commonLabels:
  environment: staging
  managed-by: argocd

commonAnnotations:
  argocd.argoproj.io/sync-wave: "0"
