apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - prometheus-deployment.yaml
  - grafana-deployment.yaml
  - configmap.yaml
  - serviceaccount.yaml

labels:
  - pairs:
      app.kubernetes.io/name: monitoring
      app.kubernetes.io/component: observability
      app.kubernetes.io/part-of: mlops-platform
    includeSelectors: false
