apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - git-repository.yaml
  - helm-repository.yaml

commonLabels:
  app.kubernetes.io/part-of: flux
  app.kubernetes.io/component: source
