apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - infrastructure-kustomization.yaml

commonLabels:
  app.kubernetes.io/part-of: flux
  app.kubernetes.io/component: kustomization
