apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namePrefix: dev-

commonLabels:
  environment: dev

patches:
  - patch: |
      - op: replace
        path: /spec/containers/0/resources/limits/cpu
        value: 500m
      - op: replace
        path: /spec/containers/0/resources/limits/memory
        value: 512Mi
    target:
      kind: ClusterServingRuntime
