apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubeflow-pipelines.fullname" . }}-api-server
  labels:
    {{- include "kubeflow-pipelines.labels" . | nindent 4 }}
    app.kubernetes.io/component: api-server
spec:
  type: {{ .Values.apiServer.service.type }}
  ports:
    - name: http
      port: {{ .Values.apiServer.service.port }}
      targetPort: http
      protocol: TCP
    - name: grpc
      port: 8887
      targetPort: grpc
      protocol: TCP
  selector:
    {{- include "kubeflow-pipelines.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api-server
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubeflow-pipelines.fullname" . }}-frontend
  labels:
    {{- include "kubeflow-pipelines.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - name: http
      port: {{ .Values.frontend.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "kubeflow-pipelines.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
