apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - source-controller.yaml
  - kustomize-controller.yaml
  - helm-controller.yaml
  - notification-controller.yaml
  - rbac.yaml

commonLabels:
  app.kubernetes.io/part-of: flux
