apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../sources
  - ../../../flux-config

patches:
  - patch: |
      - op: replace
        path: /spec/interval
        value: 1m
    target:
      kind: GitRepository
  - patch: |
      - op: replace
        path: /spec/interval
        value: 2m
    target:
      kind: Kustomization
      namespace: flux-system

commonLabels:
  environment: dev
