apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namePrefix: staging-

labels:
  - pairs:
      environment: staging
    includeSelectors: false

patches:
  - patch: |
      - op: replace
        path: /data/bucket_name
        value: kubeflow-pipelines-staging
    target:
      kind: ConfigMap
      name: kubeflow-config
