apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: flux-system

resources:
  - ../../controllers/flux-system
  - ../../controllers/argocd

commonLabels:
  environment: dev
  managed-by: flux

patches:
  - patch: |-
      - op: replace
        path: /spec/interval
        value: 1m
    target:
      kind: Kustomization
      name: ".*"
