{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kserve.fullname" . }}-manager-role
  labels:
    {{- include "kserve.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["configmaps", "events", "namespaces", "secrets", "serviceaccounts", "services"]
    verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
  - apiGroups: ["autoscaling"]
    resources: ["horizontalpodautoscalers"]
    verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
  - apiGroups: ["serving.kserve.io"]
    resources: ["inferenceservices", "inferenceservices/finalizers", "inferenceservices/status"]
    verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
  - apiGroups: ["serving.kserve.io"]
    resources: ["servingruntimes", "servingruntimes/finalizers", "servingruntimes/status"]
    verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
  - apiGroups: ["serving.kserve.io"]
    resources: ["clusterservingruntimes", "clusterservingruntimes/finalizers", "clusterservingruntimes/status"]
    verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
  - apiGroups: ["serving.kserve.io"]
    resources: ["trainedmodels", "trainedmodels/status"]
    verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
  - apiGroups: ["serving.knative.dev"]
    resources: ["services", "services/finalizers", "services/status"]
    verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
  - apiGroups: ["networking.istio.io"]
    resources: ["virtualservices"]
    verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
  - apiGroups: ["admissionregistration.k8s.io"]
    resources: ["mutatingwebhookconfigurations", "validatingwebhookconfigurations"]
    verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kserve.fullname" . }}-manager-rolebinding
  labels:
    {{- include "kserve.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "kserve.fullname" . }}-manager-role
subjects:
  - kind: ServiceAccount
    name: {{ include "kserve.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
