apiVersion: v2
name: kserve
description: KServe model serving platform for Kubernetes
type: application
version: 1.0.0
appVersion: "0.11.0"
keywords:
  - kserve
  - mlops
  - model-serving
  - inference
  - serverless
home: https://kserve.github.io/website/
sources:
  - https://github.com/kserve/kserve
maintainers:
  - name: MLOps Team
    email: mlops@company.com
dependencies:
  - name: cert-manager
    version: "1.x.x"
    repository: https://charts.jetstack.io
    condition: certManager.enabled
