apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  - prometheus-stack.yaml
  - prometheus-alerts.yaml
  - evidently-monitoring.yaml
  - drift-cronjob.yaml

commonLabels:
  app.kubernetes.io/part-of: mlops-monitoring

configMapGenerator:
  - name: grafana-dashboards-config
    files:
      - dashboards/provider.yaml
  - name: grafana-dashboards
    files:
      - dashboards/ml-monitoring-dashboard.json

generatorOptions:
  disableNameSuffixHash: true
