apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - serving-runtime.yaml
  - configmap.yaml
  - serviceaccount.yaml

labels:
  - pairs:
      app.kubernetes.io/name: kserve
      app.kubernetes.io/component: model-serving
      app.kubernetes.io/part-of: mlops-platform
    includeSelectors: false
