apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - pipeline-controller.yaml
  - configmap.yaml
  - serviceaccount.yaml

commonLabels:
  app.kubernetes.io/name: kubeflow
  app.kubernetes.io/component: pipelines
  app.kubernetes.io/part-of: mlops-platform
