apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - flux-system
  - infrastructure
  - config

commonLabels:
  environment: staging
  cluster: mlops-staging-cluster
